apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3d-volume
  #name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/d/k3dvolume