apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odbdesign-server-ingress
  # annotations:
  #   cert-manager.io/issuer: "letsencrypt-staging"
spec:
  ingressClassName: traefik
  rules:   
    - host: precision5820
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: odbdesign-server-service
                port:
                  name: ods-svc-port
          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: odbdesign-server-swaggerui-service
                port:
                  name: oss-svc-port
  # tls:
  # - hosts:
  #   - precision5820 # your domain 
  #   secretName: letsencrypt-staging-tls
