// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: symbolsdirectory.proto
// Protobuf C++ Version: 5.29.2

#ifndef symbolsdirectory_2eproto_2epb_2eh
#define symbolsdirectory_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "attrlistfile.pb.h"
#include "featuresfile.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_symbolsdirectory_2eproto ODBDESIGN_EXPORT

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct ODBDESIGN_EXPORT TableStruct_symbolsdirectory_2eproto {
  static const ::uint32_t offsets[];
};
ODBDESIGN_EXPORT extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_symbolsdirectory_2eproto;
namespace Odb {
namespace Lib {
namespace Protobuf {
class SymbolsDirectory;
struct SymbolsDirectoryDefaultTypeInternal;
ODBDESIGN_EXPORT extern SymbolsDirectoryDefaultTypeInternal _SymbolsDirectory_default_instance_;
}  // namespace Protobuf
}  // namespace Lib
}  // namespace Odb
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Odb {
namespace Lib {
namespace Protobuf {

// ===================================================================


// -------------------------------------------------------------------

class ODBDESIGN_EXPORT SymbolsDirectory final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Odb.Lib.Protobuf.SymbolsDirectory) */ {
 public:
  inline SymbolsDirectory() : SymbolsDirectory(nullptr) {}
  ~SymbolsDirectory() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SymbolsDirectory* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SymbolsDirectory));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SymbolsDirectory(
      ::google::protobuf::internal::ConstantInitialized);

  inline SymbolsDirectory(const SymbolsDirectory& from) : SymbolsDirectory(nullptr, from) {}
  inline SymbolsDirectory(SymbolsDirectory&& from) noexcept
      : SymbolsDirectory(nullptr, std::move(from)) {}
  inline SymbolsDirectory& operator=(const SymbolsDirectory& from) {
    CopyFrom(from);
    return *this;
  }
  inline SymbolsDirectory& operator=(SymbolsDirectory&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SymbolsDirectory& default_instance() {
    return *internal_default_instance();
  }
  static inline const SymbolsDirectory* internal_default_instance() {
    return reinterpret_cast<const SymbolsDirectory*>(
        &_SymbolsDirectory_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SymbolsDirectory& a, SymbolsDirectory& b) { a.Swap(&b); }
  inline void Swap(SymbolsDirectory* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SymbolsDirectory* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SymbolsDirectory* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SymbolsDirectory>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SymbolsDirectory& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SymbolsDirectory& from) { SymbolsDirectory::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SymbolsDirectory* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Odb.Lib.Protobuf.SymbolsDirectory"; }

 protected:
  explicit SymbolsDirectory(::google::protobuf::Arena* arena);
  SymbolsDirectory(::google::protobuf::Arena* arena, const SymbolsDirectory& from);
  SymbolsDirectory(::google::protobuf::Arena* arena, SymbolsDirectory&& from) noexcept
      : SymbolsDirectory(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kPathFieldNumber = 2,
    kAttrlistFileFieldNumber = 3,
    kFeatureFileFieldNumber = 4,
  };
  // optional string name = 1;
  bool has_name() const;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // optional string path = 2;
  bool has_path() const;
  void clear_path() ;
  const std::string& path() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_path(Arg_&& arg, Args_... args);
  std::string* mutable_path();
  PROTOBUF_NODISCARD std::string* release_path();
  void set_allocated_path(std::string* value);

  private:
  const std::string& _internal_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path(
      const std::string& value);
  std::string* _internal_mutable_path();

  public:
  // optional .Odb.Lib.Protobuf.AttrListFile attrlistFile = 3;
  bool has_attrlistfile() const;
  void clear_attrlistfile() ;
  const ::Odb::Lib::Protobuf::AttrListFile& attrlistfile() const;
  PROTOBUF_NODISCARD ::Odb::Lib::Protobuf::AttrListFile* release_attrlistfile();
  ::Odb::Lib::Protobuf::AttrListFile* mutable_attrlistfile();
  void set_allocated_attrlistfile(::Odb::Lib::Protobuf::AttrListFile* value);
  void unsafe_arena_set_allocated_attrlistfile(::Odb::Lib::Protobuf::AttrListFile* value);
  ::Odb::Lib::Protobuf::AttrListFile* unsafe_arena_release_attrlistfile();

  private:
  const ::Odb::Lib::Protobuf::AttrListFile& _internal_attrlistfile() const;
  ::Odb::Lib::Protobuf::AttrListFile* _internal_mutable_attrlistfile();

  public:
  // optional .Odb.Lib.Protobuf.FeaturesFile featureFile = 4;
  bool has_featurefile() const;
  void clear_featurefile() ;
  const ::Odb::Lib::Protobuf::FeaturesFile& featurefile() const;
  PROTOBUF_NODISCARD ::Odb::Lib::Protobuf::FeaturesFile* release_featurefile();
  ::Odb::Lib::Protobuf::FeaturesFile* mutable_featurefile();
  void set_allocated_featurefile(::Odb::Lib::Protobuf::FeaturesFile* value);
  void unsafe_arena_set_allocated_featurefile(::Odb::Lib::Protobuf::FeaturesFile* value);
  ::Odb::Lib::Protobuf::FeaturesFile* unsafe_arena_release_featurefile();

  private:
  const ::Odb::Lib::Protobuf::FeaturesFile& _internal_featurefile() const;
  ::Odb::Lib::Protobuf::FeaturesFile* _internal_mutable_featurefile();

  public:
  // @@protoc_insertion_point(class_scope:Odb.Lib.Protobuf.SymbolsDirectory)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 2,
      50, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SymbolsDirectory& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr path_;
    ::Odb::Lib::Protobuf::AttrListFile* attrlistfile_;
    ::Odb::Lib::Protobuf::FeaturesFile* featurefile_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_symbolsdirectory_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SymbolsDirectory

// optional string name = 1;
inline bool SymbolsDirectory::has_name() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void SymbolsDirectory::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SymbolsDirectory::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Odb.Lib.Protobuf.SymbolsDirectory.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SymbolsDirectory::set_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Odb.Lib.Protobuf.SymbolsDirectory.name)
}
inline std::string* SymbolsDirectory::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Odb.Lib.Protobuf.SymbolsDirectory.name)
  return _s;
}
inline const std::string& SymbolsDirectory::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void SymbolsDirectory::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.name_.Set(value, GetArena());
}
inline std::string* SymbolsDirectory::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* SymbolsDirectory::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Odb.Lib.Protobuf.SymbolsDirectory.name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void SymbolsDirectory::set_allocated_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Odb.Lib.Protobuf.SymbolsDirectory.name)
}

// optional string path = 2;
inline bool SymbolsDirectory::has_path() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void SymbolsDirectory::clear_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& SymbolsDirectory::path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Odb.Lib.Protobuf.SymbolsDirectory.path)
  return _internal_path();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SymbolsDirectory::set_path(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Odb.Lib.Protobuf.SymbolsDirectory.path)
}
inline std::string* SymbolsDirectory::mutable_path() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_path();
  // @@protoc_insertion_point(field_mutable:Odb.Lib.Protobuf.SymbolsDirectory.path)
  return _s;
}
inline const std::string& SymbolsDirectory::_internal_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.path_.Get();
}
inline void SymbolsDirectory::_internal_set_path(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.path_.Set(value, GetArena());
}
inline std::string* SymbolsDirectory::_internal_mutable_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.path_.Mutable( GetArena());
}
inline std::string* SymbolsDirectory::release_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Odb.Lib.Protobuf.SymbolsDirectory.path)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.path_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.path_.Set("", GetArena());
  }
  return released;
}
inline void SymbolsDirectory::set_allocated_path(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.path_.IsDefault()) {
    _impl_.path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Odb.Lib.Protobuf.SymbolsDirectory.path)
}

// optional .Odb.Lib.Protobuf.AttrListFile attrlistFile = 3;
inline bool SymbolsDirectory::has_attrlistfile() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.attrlistfile_ != nullptr);
  return value;
}
inline const ::Odb::Lib::Protobuf::AttrListFile& SymbolsDirectory::_internal_attrlistfile() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Odb::Lib::Protobuf::AttrListFile* p = _impl_.attrlistfile_;
  return p != nullptr ? *p : reinterpret_cast<const ::Odb::Lib::Protobuf::AttrListFile&>(::Odb::Lib::Protobuf::_AttrListFile_default_instance_);
}
inline const ::Odb::Lib::Protobuf::AttrListFile& SymbolsDirectory::attrlistfile() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Odb.Lib.Protobuf.SymbolsDirectory.attrlistFile)
  return _internal_attrlistfile();
}
inline void SymbolsDirectory::unsafe_arena_set_allocated_attrlistfile(::Odb::Lib::Protobuf::AttrListFile* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.attrlistfile_);
  }
  _impl_.attrlistfile_ = reinterpret_cast<::Odb::Lib::Protobuf::AttrListFile*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Odb.Lib.Protobuf.SymbolsDirectory.attrlistFile)
}
inline ::Odb::Lib::Protobuf::AttrListFile* SymbolsDirectory::release_attrlistfile() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::Odb::Lib::Protobuf::AttrListFile* released = _impl_.attrlistfile_;
  _impl_.attrlistfile_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Odb::Lib::Protobuf::AttrListFile* SymbolsDirectory::unsafe_arena_release_attrlistfile() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Odb.Lib.Protobuf.SymbolsDirectory.attrlistFile)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::Odb::Lib::Protobuf::AttrListFile* temp = _impl_.attrlistfile_;
  _impl_.attrlistfile_ = nullptr;
  return temp;
}
inline ::Odb::Lib::Protobuf::AttrListFile* SymbolsDirectory::_internal_mutable_attrlistfile() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.attrlistfile_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Odb::Lib::Protobuf::AttrListFile>(GetArena());
    _impl_.attrlistfile_ = reinterpret_cast<::Odb::Lib::Protobuf::AttrListFile*>(p);
  }
  return _impl_.attrlistfile_;
}
inline ::Odb::Lib::Protobuf::AttrListFile* SymbolsDirectory::mutable_attrlistfile() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::Odb::Lib::Protobuf::AttrListFile* _msg = _internal_mutable_attrlistfile();
  // @@protoc_insertion_point(field_mutable:Odb.Lib.Protobuf.SymbolsDirectory.attrlistFile)
  return _msg;
}
inline void SymbolsDirectory::set_allocated_attrlistfile(::Odb::Lib::Protobuf::AttrListFile* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.attrlistfile_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.attrlistfile_ = reinterpret_cast<::Odb::Lib::Protobuf::AttrListFile*>(value);
  // @@protoc_insertion_point(field_set_allocated:Odb.Lib.Protobuf.SymbolsDirectory.attrlistFile)
}

// optional .Odb.Lib.Protobuf.FeaturesFile featureFile = 4;
inline bool SymbolsDirectory::has_featurefile() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.featurefile_ != nullptr);
  return value;
}
inline const ::Odb::Lib::Protobuf::FeaturesFile& SymbolsDirectory::_internal_featurefile() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Odb::Lib::Protobuf::FeaturesFile* p = _impl_.featurefile_;
  return p != nullptr ? *p : reinterpret_cast<const ::Odb::Lib::Protobuf::FeaturesFile&>(::Odb::Lib::Protobuf::_FeaturesFile_default_instance_);
}
inline const ::Odb::Lib::Protobuf::FeaturesFile& SymbolsDirectory::featurefile() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Odb.Lib.Protobuf.SymbolsDirectory.featureFile)
  return _internal_featurefile();
}
inline void SymbolsDirectory::unsafe_arena_set_allocated_featurefile(::Odb::Lib::Protobuf::FeaturesFile* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.featurefile_);
  }
  _impl_.featurefile_ = reinterpret_cast<::Odb::Lib::Protobuf::FeaturesFile*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Odb.Lib.Protobuf.SymbolsDirectory.featureFile)
}
inline ::Odb::Lib::Protobuf::FeaturesFile* SymbolsDirectory::release_featurefile() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::Odb::Lib::Protobuf::FeaturesFile* released = _impl_.featurefile_;
  _impl_.featurefile_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Odb::Lib::Protobuf::FeaturesFile* SymbolsDirectory::unsafe_arena_release_featurefile() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Odb.Lib.Protobuf.SymbolsDirectory.featureFile)

  _impl_._has_bits_[0] &= ~0x00000008u;
  ::Odb::Lib::Protobuf::FeaturesFile* temp = _impl_.featurefile_;
  _impl_.featurefile_ = nullptr;
  return temp;
}
inline ::Odb::Lib::Protobuf::FeaturesFile* SymbolsDirectory::_internal_mutable_featurefile() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.featurefile_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Odb::Lib::Protobuf::FeaturesFile>(GetArena());
    _impl_.featurefile_ = reinterpret_cast<::Odb::Lib::Protobuf::FeaturesFile*>(p);
  }
  return _impl_.featurefile_;
}
inline ::Odb::Lib::Protobuf::FeaturesFile* SymbolsDirectory::mutable_featurefile() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000008u;
  ::Odb::Lib::Protobuf::FeaturesFile* _msg = _internal_mutable_featurefile();
  // @@protoc_insertion_point(field_mutable:Odb.Lib.Protobuf.SymbolsDirectory.featureFile)
  return _msg;
}
inline void SymbolsDirectory::set_allocated_featurefile(::Odb::Lib::Protobuf::FeaturesFile* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.featurefile_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }

  _impl_.featurefile_ = reinterpret_cast<::Odb::Lib::Protobuf::FeaturesFile*>(value);
  // @@protoc_insertion_point(field_set_allocated:Odb.Lib.Protobuf.SymbolsDirectory.featureFile)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protobuf
}  // namespace Lib
}  // namespace Odb


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // symbolsdirectory_2eproto_2epb_2eh
