The default units of measurement for the product model are as defined in the UNITS directive in the file
misc/info of the product model. If the default is not defined for the product model, the default is imperial.
For newly created files, units are based on the default defined for the product model.
For each file described in this document, there is a table of information. The UNITS row of the file
information table indicates whether the UNITS directive is required for that file:
<file_name>
Type One of these strings:
• Line Record Text
• Structured Text
Compression One of these strings:
• None
• Yes
Path Path to the file.
UNITS One of these strings:
• The UNITS directive is required.
• The UNITS directive is not relevant for the <file_name> file.
Files that Must Contain the UNITS Directive
File Name Path
info <product_model_name>/misc
ODB++Design Format Specification 23
ODB++Design Format Specification
Units of Measurement
File Name Path
sysattr
sysattr.dfm
sysattr.fab
sysattr.assy
sysattr.test
sysattr.gen
userattr
<product_model_name>/misc
attrlist <product_model_name>/misc
<product_model_name>/steps/<step_name>
<product_model_name>/steps/<step_name>/layers/<layer_name>
<product_model_name>/symbols/<symbol_name>
<product_model_name>/wheels/<wheel_name>
stephdr <product_model_name>/steps/<step_name>
profile <product_model_name>/steps/<step_name>
<product_model_name>/steps/<step_name>/layers/<layer_name>
data <product_model_name>/steps/<step_name>/eda
features <product_model_name>/steps/<step_name>/layers/<layer_name>
<product_model_name>/symbols/<symbol_name>
tools <product_model_name>/steps/<step_name>/layers/<layer_name>
components <product_model_name>/steps/<step_name>/layers/comp_+_top
<product_model_name>/steps/<step_name>/layers/comp_+_bot
netlist <product_model_name>/steps/<step_name>/netlists/cadnet
<product_model_name>/steps/<step_name>/netlists/refnet
How Measurements Are Stored
According to the unit of measurement selected, data is stored in these units:
Type of Data Metric (UNITS=MM) Imperial (UNITS=INCH)
area square mm square inch
copper weight µm
In metric units, copper weight is
actually copper thickness. The
application converts it accordingly
into commonly used neutral units
(thickness or weight).
ounce per square foot
24 ODB++Design Format Specification
ODB++Design Format Specification
Units of Measurement
Type of Data Metric (UNITS=MM) Imperial (UNITS=INCH)
current amps amps
distances, sizes,
coordinates
mm inch
resistance ohm ohm
temperature centigrade fahrenheit
voltage volts volts
weight gram ounce
How the UNITS Directive Specifies Units of Measurement
Location of UNITS
Directive Scope Example
There is no
UNITS directive in
<product_model>/mi
sc/info.
The default units of
measurement for
the product model is
imperial units.
None
There is a UNITS
directive in
<product_model>/mi
sc/info.
The units of
measurement
specified in this UNITS
directive is the default
for the product model.
info file example:
JOB_NAME=odbv_demo_mm
ODB_VERSION_MAJOR=8
ODB_VERSION_MINOR=1
ODB_SOURCE=
CREATION_DATE=20170913.130051
SAVE_DATE=20170914.132825
SAVE_APP=Valor NPI 10.1
SAVE_USER=roni
UNITS=MM
MAX_UID=431990
If there is a UNITS
directive in a file
that supports it, and
there are no other
specifications of units
of measurement in the
file.
The units of
measurement
specified in the UNITS
directive is used for all
measurements in the
file.
stephdr file example:
UNITS=INCH
X_DATUM=0
Y_DATUM=0
X_ORIGIN=0
Y_ORIGIN=0
TOP_ACTIVE=0
BOTTOM_ACTIVE=0
RIGHT_ACTIVE=0
LEFT_ACTIVE=0
AFFECTING_BOM=
AFFECTING_BOM_CHANGED=0
ID=0
ODB++Design Format Specification 25
ODB++Design Format Specification
Units of Measurement
Location of UNITS
Directive Scope Example
There is a UNITS
directive in a file
that supports it, and
individual records in
the file also specify
units of measurement.
The units of
measurement
specified in the UNITS
directive is used
except where this
is overridden by the
specification in an
individual record in the
file.
features file example:
The "I" at the end of the symbol definition line
specifies imperial units. This overrides the
specification of UNITS=MM.
UNITS=MM
ID=616
#
#Num Features
#
F 12397
#
#Feature symbol names
$0 oval210x170 I
