##################################################################################################
# OdbDesignServer gRPC service (k3d ServiceLB / klipper-lb)
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: odbdesign-server-grpc-service
  labels:
    app: odbdesign-server
    service: odbdesign-server-grpc
spec:
  type: LoadBalancer
  ports:
    - name: ods-grpc-port
      port: 50051
      targetPort: ods-grpc-port
      protocol: TCP
  selector:
    app: odbdesign-server

