name: SBOM Generate and Submit

on:
  push:
    branches: [ "main", "release", "development", "nam20485" ]
  workflow_dispatch:

permissions:
    contents: read

jobs:
  build:
    name: Generate-Submit-SBOM
    runs-on: ubuntu-22.04
    permissions: 
        id-token: write
        contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: SBOM Generate
        uses: advanced-security/sbom-generator-action@375dee8e6144d9fd0ec1f5667b4f6fb4faacefed # v0.0.1
        id: sbom-generate
        env: 
          GITHUB_TOKEN: ${{ github.token }}

      - name: SBOM Upload 
        uses: advanced-security/spdx-dependency-submission-action@dc069b56ba31ce546dc419b549aceb808c632d9a # v0.0.1
        with:
            filePath: ${{ steps.sbom-generate.outputs.fileName }}
     