name: SBOM Generate and Submit

on:
  push:
    branches: [ "main", "release", "development", "staging", "nam20485" ]
  workflow_dispatch:

permissions:
    contents: read

jobs:
  build:
    name: Generate-Submit-SBOM
    runs-on: ubuntu-22.04
    permissions: 
        id-token: write
        contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: SBOM Generate
        uses: advanced-security/sbom-generator-action@375dee8e6144d9fd0ec1f5667b4f6fb4faacefed # v0.0.1
        id: sbom-generate
        env: 
          GITHUB_TOKEN: ${{ github.token }}

      - name: SBOM Upload 
        uses: advanced-security/spdx-dependency-submission-action@dc069b56ba31ce546dc419b549aceb808c632d9a # v0.0.1
        with:
            filePath: ${{ steps.sbom-generate.outputs.fileName }}
     